[package]
name = "kaleidoscope"
version = "0.1.0"
authors = ["Justus K <justus.k@protonmail.com>"]
edition = "2018"

[dependencies]
logos = "0.11.4"
salsa = "0.15.0"
smol_str = "0.1.16"
codespan-reporting = "0.9.5"
